### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Arshitha**
adding brainhack badge to main README

### CODE REVIEW

**Comment by Arshitha** [comment]
It'd look nicer if all the badges could be on the same line. Looks like this for now:
Screen Shot 2023-01-04 at 1 09 48 PM

**Comment by ericearl** [comment]
> It'd look nicer if all the badges could be on the same line. Looks like this for now:
> Screen Shot 2023-01-04 at 1 09 48 PM
> 

Good idea. It might work if you put it on line two or three or six?

**Comment by Arshitha** [comment]
Adding it between `<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->` and `<!-- ALL-CONTRIBUTORS-BADGE:END -->` seems to be the only way to have them both on the same line. The other suggestions didn't work. I'm not sure if it'll affect all-contributors section but if it does then we can remove the Brainhack badge from the main README

**Comment by ericearl** [comment]
Looks like all-contributors has an issue for just this badge business. For now, I will update the all-contributors badge to be in line together myself each time I add a new contributor.

**Comment by Arshitha** [comment]
ok sounds good! I'll let you resolve the conflict and merge it.

**Comment by ericearl** [comment]
Done and merged, thanks @Arshitha!

**Pull request merged**
